from typing import Protocol


class StoragePort(Protocol):
    async def presign_put(self, *, profile: str, key: str, expires_in: int) -> str: ...

    async def presign_get(self, *, profile: str, key: str, expires_in: int) -> str: ...

    async def head(self, *, profile: str, key: str) -> int | None: ...

    async def delete(self, *, profile: str, key: str) -> None: ...

    async def write(self, *, profile: str, key: str, payload: bytes) -> int: ...

    async def read(self, *, profile: str, key: str) -> bytes | None: ...

    def key_for(self, *, owner_id: str, item_id: str) -> str: ...
