IDENTITIES = "chat_identities"
CONVERSATIONS = "chat_conversations"
KEYS = "chat_conversation_keys"
MESSAGES = "chat_messages"
READS = "chat_reads"

USERS = "users"
CONNECTIONS = "connections"

ACCEPTED = "accepted"
PENDING = "pending"

MESSAGE_MAX_LIMIT = 50
MESSAGE_DEFAULT_LIMIT = 30
CONVERSATION_LIMIT = 100
CIPHERTEXT_MAX_CHARS = 8192
EMOJI_MAX_CHARS = 8

PRESENCE_TTL_SECONDS = 60
TYPING_TTL_SECONDS = 6

EDIT_WINDOW_SECONDS = 600
